services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.Ignition-PDX178.entrypoints: "web"
      traefik.http.routers.Ignition-PDX178.rule: "Host(`Ignition-PDX178.localtest.me`)"
      traefik.http.services.Ignition-PDX178.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: Ignition-PDX178
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: Ignition-PDX178.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
